Format source with black --line-length=79
Fixes flake8 failures:  "E501 line too long":

    tests/drc_test_utils/mock_registry.py:106:80: E501 line too long (93 > 79 characters)

    ERROR: InvocationError for command [...]/docker-registry-client/.tox/lint/bin/flake8
    docker_registry_client tests setup.py (exited with code 1)

Some flake8 errors are too strict, and disabled in the `.flake8` file:
E231 missing whitespace after ','
E203 whitespace before ':'
E231 missing whitespace after ','; conflicts with black formatting